import {createStore} from 'vuex'
export default createStore({
    state:{
        loginUserInfo:null,
        showLogin:false,
        boardList:[],
        articlePboard:0,
        articleBoard:0,
        messageCount:{},
        sysSetting:{}
    },
    getters:{
        
    },
    mutations:{
        updateLoginUserInfo(state,value){
            state.loginUserInfo=value
        },
        showLogin(state,value){
            state.showLogin=value
        },
        setBoardList(state,value){
            state.boardList=value
        },
        setArticlePboard(state,value){
            state.articlePboard=value
        },
        setArticleBoard(state,value){
            state.articleBoard=value
        },
        updateMessageCount(state,value){
            state.messageCount=value
        },
        readMessage(state,value){
            state.messageCount.total=state.messageCount.total-state.messageCount[value]
            state.messageCount[value]=0
        },
        saveSysSetting:(state,value)=>{
            state.sysSetting=value
        }
    },
    actions:{}
})