import {createStore} from 'vuex'
export default createStore({
    state:{
        loginUserInfo:'',
        showLogin:false,
        boardList:[],
        articlePboard:'',
        articleBoard:''
    },
    getters:{},
    mutations:{
        updateLoginUserInfo(state,value){
            state.loginUserInfo=value
        },
        showLogin(state,value){
            state.showLogin=value
        },
        setBoardList(state,value){
            state.boardList=value
        },
        setArticlePboard(state,value){
            state.articlePboard=value.pBoard
        },
        setArticleBoard(state,value){
            state.articleBoard=value.board
        },
    },
    actions:{}
})